reset;
model apery_set_member_lagr.mod;
data numerical_semigroup.dat;
let s := 30;
let i := 6;
let lambda := 0;
param it default 0;
option solver gurobi;
solve;
let rest := abs(sum {j in N} a[j]*X[j] - i - s*K);
repeat {
    let lambda := lambda + rest;
    solve;
    let rest := abs(sum {j in N} a[j]*X[j] - i - s*K);
    let it := it + 1;
} while rest != 0;
display it;
display lambda;
